### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [Statonwest/VR_Ambilight#1]
Hello!

I found this project from https://hackaday.com/2023/07/09/enhance-vr-immersion-by-shoehorning-an-ambilight-into-a-headset/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code and images in any purpose?
It would be great to see any popular open source license.

**Comment by Statonwest** [comment]
Thank you for the feedback. A license has been added.

**Comment by vazhnov** [comment]
GPL v3.0 — great! Thank you!
