### ISSUE TITLE
Potential improvements

### ISSUE THREAD

**Issue by Nemernemer** [Statonwest/VR_Ambilight#2]
Hello!

Apologies if this is the wrong way to go about this, I am not used to Github etiquette.
I followed your project, and I think I have some improvements.

1: Instead of mounting the LEDs on the face gasket, I found it more convenient to instead place them against the raised edge on the unit itself. This had both the benefit of the LEDs being more in view, and the convenience of being able to remove the gasket for cleaning without taking along the electronics. I am using the silicone cast version of WS2812Bs, which helps protect against accidental scratching when removing the face gasket.

2: Instead of using a diffusion sheet, I designed a 3d-print which you make out of a translucent filament (in my case clear ABS) and glue two layers of paper onto. This too is just held in place between the gasket and the silicone surrounding the lenses. This allowed me to run the LEDs significantly brighter (50%) without them blinding the user, which in turn gives a considerably higher color depth, mitigating a lot of the erratic flashing experienced at 10-25%. (Unfortunately this takes away ~2mm from the upper eye distance adjustment, but does not prohibit the back and forth adjustment.)

I have attached two images of my implementation, and the STEP file for the 3D print, if that is of interest.

![P_20230810_234907](https://github.com/Statonwest/VR_Ambilight/assets/64172689/15f33d66-b7de-43da-b2a2-bd1c40770d02)
![P_20230810_235154](https://github.com/Statonwest/VR_Ambilight/assets/64172689/9937338c-2f5a-41f5-9f3a-d218a1cf7dc4)

(Diffuser printed at 0.86mm line widths with a 0.6mm nozzle, creating two solid walls. 0.16 layer height)
[Diffuser.zip](https://github.com/Statonwest/VR_Ambilight/files/12317541/Diffuser.zip)

**Comment by Statonwest** [comment]
Thanks for reaching out. I dig the improvements. This is my first real repository so the etiquette is new to me to.If you can clone the repo, add your changes to it, and then submit a merge request, I can add it to the main branch. That way you'll also get the credit.

**Comment by Statonwest** [comment]
Thanks for reaching out. I dig the improvements. This is my first real repository so the etiquette is new to me to.If you can clone the repo, add your changes to it, and then submit a merge request, I can add it to the main branch. That way you'll also get the credit.
