### ISSUE TITLE
Different Screen Capture Software

### ISSUE THREAD

**Issue by elbrodark** [Statonwest/VR_Ambilight#4]
Hi,
Nice Project, the mounting inside the headset works perfectly via the 3dprinted Diffuser, i glued the LED directly to the Diffuser, so nothing gets "broken" inside the Headset.

For the Software i switched from "Prismatik" to "Firefly Luciferin" (https://github.com/sblantipodi/firefly_luciferin) cause it´s not so extremly ressource hungry like Prismatik and it also works via wifi.

**Comment by Statonwest** [comment]
Thanks for your input. Firefly has been added.
